name: synseam-backend

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=synseam
      - CORS_ORIGIN=http://localhost:3000
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
      - MAIL_USER=
      - MAIL_PASS=
      - MAIL_FROM=hello@synseam.co
      - NOTIFY_EMAIL=hello@synseam.co
    depends_on:
      - db
      - mailpit
    networks:
      - synseam_net

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=synseam
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - synseam_net

  mailpit:
    image: axllent/mailpit
    restart: always
    ports:
      - '8025:8025' # Web UI
      - '1025:1025' # SMTP
    networks:
      - synseam_net

networks:
  synseam_net:
    name: synseam_net
    driver: bridge

volumes:
  pgdata:
